//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDeviceBind
    {
        public int id { get; set; }
        public string openId { get; set; }
        public string token { get; set; }
        public string deviceId { get; set; }
        public Nullable<bool> state { get; set; }
        public string mac { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public string deviceAvatar { get; set; }
        public string deviceName { get; set; }
        public string userPhone { get; set; }
    }
}
